# Generated by Django 2.1.3 on 2018-11-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_get_index(king_admin)', '可以访问 king_admin 首页02'), ('can_get_table_objs(king_admin)', '可以访问 king_admin 各个表02'), ('can_post_table_objs(king_admin)', '可以修改 king_admin 每个表中对象02'), ('can_get_edit_detail(king_admin)', '可以查看 king_admin 对应表详细信息02'), ('can_post_edit_detail(king_admin)', '可以修改 king_admin 对应表详细信息02'), ('can_get_change_pwd(king_admin)', '可以查看 king_admin 修改密码页面02'), ('can_post_change_pwd(king_admin)', '可以修改 king_admin 密码02'), ('can_get_obj_field_delete(king_admin)', '可以查看 king_admin 删除页面02'), ('can_post_obj_field_delete(king_admin)', '可以修改 king_admin 删除页面数据02'), ('can_get_obj_table_obj_add(king_admin)', '可以查看 king_admin 新增页面02'), ('can_post_obj_table_obj_add(king_admin)', '可以修改 king_admin 新增页面数据02')), 'verbose_name_plural': 'CRM账户'},
        ),
    ]
